// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "Home", "home next page hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is the intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or in any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Apple.html", "Apple", "apple nbsp common fruit found on trees all around hyrule eat it fresh or cook to increase effect commonly in field east necludia next material hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is the intellectual property nintendo co ltd this project not affiliated associated authorized endorsed any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Palm_Fruit.html", "Palm Fruit", "palm fruit nbsp from trees that grow near the ocean it doesn offer any special effects but will increase your heart recovery when used as an ingredient commonly found in east necluda gerudo desert last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Wildberry.html", "Wildberry", "wildberry nbsp fruit that grows in cold snowy regions known for its tangy sweet flavor it doesn offer any effects but popular cooking ingredient commonly found gerudo highlands hebra mountains last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is the intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or way officially connected with subsidiaries ", "");
   this[database_length++] = new SearchPage("Hearty_Durian.html", "Hearty Durian", "hearty durian nbsp this fruit mighty odor has earned it the nickname quot king of fruits offers immense restorative powers dished cooed with will temporarily increase your maximum hearts commonly found in west necludia faron grasslands last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend zelda series is intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected its subsidiaries ", "");
   this[database_length++] = new SearchPage("Hydomelon.html", "Hydromelon", "hydromelon nbsp hydomelon this resilient fruit can flourish even in the heat of desert hydrating liquid inside provides cooling effect that when cooked increases your resistance commonly found gerudo faron grasslands last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend zelda series is intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Spicy_Pepper.html", "Spicy Pepper", "spicy pepper nbsp this is exploding with spice cook it to create dishes that will raise your body temperature and help you withstand the cold commonly found in gerudo desert tabantha frontier last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected its subsidiaries ", "");
   this[database_length++] = new SearchPage("Voltfruit.html", "Voltfruit", "voltfruit nbsp cacti found in the gerudo desert bear this sweet fruit it naturally insulated so when cooked into dish provides resistance against electricity commonly highlands can be purchased town last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Fleet_Lotus_Seeds.html", "Fleet Lotus Seeds", "fleet lotus seeds nbsp the plant that bears these grows near deep water roots draw nutrients from which boosts your movement speed when are cooked into dish commonly found in lanayru wetlands great spring last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Mighty_Bananas.html", "Mighty Bananas", "mighty bananas nbsp this fruit grows mainly in tropical forests of the faron region when it used as an ingredient resulting dish will temporarily increase your attack power commonly found yiga clan hideout last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend zelda series is intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Hylian_Shroom.html", "Hylian Shroom", "hylian shroom nbsp common mushroom found near trees around hyrule eat it to restore half heart commonly in field west necluda last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is the intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Endura_Shroom.html", "Endura Shroom", "endura shroom nbsp rare yellowish orange mushroom cook it before eating to temporarily increase your stamina limit commonly found in hyrule ridge field last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is the intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Stamella_Shroom.html", "Stamella Shroom", "stamella shroom nbsp green mushroom that grows near trees in the forest it chock full of natural energy cook to release its stamina restoration properties commonly found hyrule ridge field last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend zelda series is intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or any way officially connected with subsidiaries ", "");
   this[database_length++] = new SearchPage("Hearty_Truffle.html", "Hearty Truffle", "hearty truffle nbsp this rare mushroom has rich scent cook it before eating to temporarily increase your maximum hearts commonly found in great hyrule forest field purchase hateno village last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is the intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Big_Hearty_Truffle.html", "Big Hearty Truffle", "big hearty truffle nbsp years of going unpicked have allowed this to grow quite large it chock full nutrients when cooked into dish temporarily increases your maximum hearts commonly found in hebra mountains great hyrule forest last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend zelda series is the intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Chillshroom.html", "Chillshroom", "chillshroom nbsp often found at the base of pine trees in cold climates these mushrooms are cool to touch and can be used cook dishes that allow you stay even arid regions commonly hebra mountains mount lanayru purchased gerudo town last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend zelda series is intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Sunshroom.html", "Sunshroom", "sunshroom nbsp bright red mushroom that grows in hot climates imbued with the power of heat they can be used took dishes will allow you to endure bitter cold commonly found eldin canyon gerudo highlands purchased town last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend zelda series is intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or any way officially connected its subsidiaries ", "");
   this[database_length++] = new SearchPage("Zapshroom.html", "Zapshroom", "zapshroom nbsp this mushroom grows wild in the gerudo region cap is naturally insulated so when used cooking it will offer protection against electricity commonly found deep akkala highlands can be purchased town last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Rushroom.html", "Rushroom", "rushroom nbsp mushroom that can grow almost anywhere but prefers ceilings and sheer cliffs cook it before eating to temporarily increase your movement speed commonly found in gerudo highlands hyrule ridge last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is the intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Razorshroom.html", "Razorshroom", "razorshroom nbsp this mushroom is known for the natural slice in its cap eating it fosters your competitive spirit use when cooking to prepare dish that will increase strength commonly found great hyrule forest tabantha frontier last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with subsidiaries ", "");
   this[database_length++] = new SearchPage("Ironshroom.html", "Ironshroom", "ironshroom nbsp the cap of this mushroom is very hard use it when cooking to prepare dish that increases your defense commonly found in west necluda east can be purchased gerudo town last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend zelda series intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Silent_Shroom.html", "Silent Shroom", "silent shroom nbsp strange mushroom that glows softly in the forest at night cooking it into dish unlocks nutrients its cap resulting meal will allow you to move stealthily commonly found lanaryu great spring west necluda last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or any way officially connected with subsidiaries ", "");
   this[database_length++] = new SearchPage("Hyrule_Herb.html", "Hyrule Herb", "hyrule herb nbsp this healthy grows abundantly in the plains of cook it before eating to increase number hearts restored commonly found field akkala highlands last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend zelda series is intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Hearty_Radish.html", "Hearty Radish", "hearty radish nbsp rare that grows in the sunny plains cook it before eating to temporarily increase your maximum hearts commonly found hyrule ridge west necluda can be purchased from beedle at east akkla stable last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Big_Hearty_Radish.html", "Big Hearty Radish", "big hearty radish nbsp this has grown much larger than the average it rich in analeptic compounds that when cooked into dish temporarily increase your maximum hearts commonly found akkala highlands lanaryu great springs last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Cool_Safflina.html", "Cool Safflina", "cool safflina nbsp this medicinal plant grows in high elevations such as mountains the hebra or gerudo regions when cooked into dish it will temporarily increase your heat resistance commonly found highlands surrounding great fairy fountain gurudo wasteland last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is intellectual property nintendo co ltd project not affiliated associated authorized endorsed any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Warm_Safflina.html", "Warm Safflina", "warm safflina nbsp this medicinal plant grows in hot regions such as the gerudo desert it to touch and increases your cold resistance when cooked into dish commonly found hyrule ridge surrounding great fairy fountain gurudo wasteland last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Electric_Safflina.html", "Electric Safflina", "electric safflina nbsp this medicinal plant grows abundantly in the gerudo desert its particular fibers conduct electricity which will increase your resistance when cooked into dish commonly found hyrule ridge last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with subsidiaries ", "");
   this[database_length++] = new SearchPage("Swift_Carrot.html", "Swift Carrot", "swift carrot nbsp this is cultivated extensively in kakariko village it strengthens the legs and hips when cooked into dish which helps increase your movement speed commonly found can be purchased from beedle east akkala stable woodland satble last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Endura_Carrot.html", "Endura Carrot", "endura carrot nbsp highly valued as medicinal plant the contains large amounts of nourishing energy when cooked into dish it boosts your stamina beyond its maximum limit commonly found in hyrule ridge faron grasslands behind great fairy fountain near kakariko village last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend zelda series is intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or any way officially connected with subsidiaries ", "");
   this[database_length++] = new SearchPage("Fortified_Pumpkin.html", "Fortified Pumpkin", "fortified pumpkin nbsp an extremely tough raised in village fields when cooked that toughness manifests itself by considerably upping defense commonly found kakariko last material next hylia serif font made artsy omni http artsyomni com hyliaserifthe legend of zelda series is the intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Swift_Violet.html", "Swift Violet", "swift violet nbsp this vitality rich flower blooms mainly on cliffsides when cooked into dish the nourishing compounds increase your movement speed commonly found in gerudo highlands hebra mountains zora domain last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Mighty_Thistle.html", "Mighty Thistle", "mighty thistle nbsp this medicinal plant is know for its sharp thorns and the fruit it bears contains compound that increases attack power when cooked into dish commonly found in west necluda faron grasslands surrounding great fairy fountain southeast of tabantha tower last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend zelda series intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with subsidiaries ", "");
   this[database_length++] = new SearchPage("Armoranth.html", "Armoranth", "armoranth nbsp this tough medicinal plant cannot be broken but it can cooked its durable yet flexible fibers raise your defense when into dish commonly found in akkala highlands hyrule ridge last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend of zelda series is the intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with subsidiaries ", "");
   this[database_length++] = new SearchPage("Blue_Nightshade.html", "Blue Nightshade", "blue nightshade nbsp plant that grows in quieter areas of hyrule at night it gives off soft glow cook with to increase your stealth commonly found west necluda lanaryu great spring can be near the fairy by kakariko village last material next hylia serif font made artsy omni http artsyomni com hyliaserifthe legend zelda series is intellectual property nintendo co ltd this project not affiliated associated authorized endorsed or any way officially connected its subsidiaries ", "");
   this[database_length++] = new SearchPage("Silent_Princess.html", "Slient Princess", "slient princess nbsp silent this lovely flower was said to have been favorite of the hyrule once feared gone extinct it recently spotted growing in wild commonly found west necluda ridge last material next hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend zelda series is intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   this[database_length++] = new SearchPage("Courser_Bee_Honey.html", "Courser Bee Honey", "courser bee honey nbsp straight from the hive is chock full of nutrients cooking this into meal unlocks potential these and provides stamina recovery effect commonly found in hyrule field tabantha frontier last material hylia serif font made by artsy omni http artsyomni com hyliaserifthe legend zelda series intellectual property nintendo co ltd project not affiliated associated authorized endorsed or any way officially connected with its subsidiaries ", "");
   return this;
}
